// Índice de TODOS os 15 frames por espécie.
// O Metro (bundler do Expo) exige require() com caminho literal — não dá para montar
// o path dinamicamente. Por isso cada arquivo é listado explicitamente.
//
// A ordem 0–14 segue o padrão do Digital Monster Ver. 20th. O significado de cada
// índice está documentado em animation-map.ts (FRAME).

import type { SpriteSource } from './types'
import type { DigimonSpecies } from '@/domain/shared/types'

export const FRAMES: Record<DigimonSpecies, SpriteSource[]> = {
  // Fases do ovo — compartilhadas por todas as linhas evolutivas
  egg1: [
    require('@/assets/digimon/egg1/0.png'),
    require('@/assets/digimon/egg1/1.png'),
    require('@/assets/digimon/egg1/2.png'),
    require('@/assets/digimon/egg1/3.png'),
    require('@/assets/digimon/egg1/4.png'),
    require('@/assets/digimon/egg1/5.png'),
    require('@/assets/digimon/egg1/6.png'),
    require('@/assets/digimon/egg1/7.png'),
    require('@/assets/digimon/egg1/8.png'),
    require('@/assets/digimon/egg1/9.png'),
    require('@/assets/digimon/egg1/10.png'),
    require('@/assets/digimon/egg1/11.png'),
    require('@/assets/digimon/egg1/12.png'),
    require('@/assets/digimon/egg1/13.png'),
    require('@/assets/digimon/egg1/14.png'),
  ],
  egg2: [
    require('@/assets/digimon/egg2/0.png'),
    require('@/assets/digimon/egg2/1.png'),
    require('@/assets/digimon/egg2/2.png'),
    require('@/assets/digimon/egg2/3.png'),
    require('@/assets/digimon/egg2/4.png'),
    require('@/assets/digimon/egg2/5.png'),
    require('@/assets/digimon/egg2/6.png'),
    require('@/assets/digimon/egg2/7.png'),
    require('@/assets/digimon/egg2/8.png'),
    require('@/assets/digimon/egg2/9.png'),
    require('@/assets/digimon/egg2/10.png'),
    require('@/assets/digimon/egg2/11.png'),
    require('@/assets/digimon/egg2/12.png'),
    require('@/assets/digimon/egg2/13.png'),
    require('@/assets/digimon/egg2/14.png'),
  ],
  botamon: [
    require('@/assets/digimon/botamon/0.png'),
    require('@/assets/digimon/botamon/1.png'),
    require('@/assets/digimon/botamon/2.png'),
    require('@/assets/digimon/botamon/3.png'),
    require('@/assets/digimon/botamon/4.png'),
    require('@/assets/digimon/botamon/5.png'),
    require('@/assets/digimon/botamon/6.png'),
    require('@/assets/digimon/botamon/7.png'),
    require('@/assets/digimon/botamon/8.png'),
    require('@/assets/digimon/botamon/9.png'),
    require('@/assets/digimon/botamon/10.png'),
    require('@/assets/digimon/botamon/11.png'),
    require('@/assets/digimon/botamon/12.png'),
    require('@/assets/digimon/botamon/13.png'),
    require('@/assets/digimon/botamon/14.png'),
  ],
  koromon: [
    require('@/assets/digimon/koromon/0.png'),
    require('@/assets/digimon/koromon/1.png'),
    require('@/assets/digimon/koromon/2.png'),
    require('@/assets/digimon/koromon/3.png'),
    require('@/assets/digimon/koromon/4.png'),
    require('@/assets/digimon/koromon/5.png'),
    require('@/assets/digimon/koromon/6.png'),
    require('@/assets/digimon/koromon/7.png'),
    require('@/assets/digimon/koromon/8.png'),
    require('@/assets/digimon/koromon/9.png'),
    require('@/assets/digimon/koromon/10.png'),
    require('@/assets/digimon/koromon/11.png'),
    require('@/assets/digimon/koromon/12.png'),
    require('@/assets/digimon/koromon/13.png'),
    require('@/assets/digimon/koromon/14.png'),
  ],
  agumon: [
    require('@/assets/digimon/agumon/0.png'),
    require('@/assets/digimon/agumon/1.png'),
    require('@/assets/digimon/agumon/2.png'),
    require('@/assets/digimon/agumon/3.png'),
    require('@/assets/digimon/agumon/4.png'),
    require('@/assets/digimon/agumon/5.png'),
    require('@/assets/digimon/agumon/6.png'),
    require('@/assets/digimon/agumon/7.png'),
    require('@/assets/digimon/agumon/8.png'),
    require('@/assets/digimon/agumon/9.png'),
    require('@/assets/digimon/agumon/10.png'),
    require('@/assets/digimon/agumon/11.png'),
    require('@/assets/digimon/agumon/12.png'),
    require('@/assets/digimon/agumon/13.png'),
    require('@/assets/digimon/agumon/14.png'),
  ],
  greymon: [
    require('@/assets/digimon/greymon/0.png'),
    require('@/assets/digimon/greymon/1.png'),
    require('@/assets/digimon/greymon/2.png'),
    require('@/assets/digimon/greymon/3.png'),
    require('@/assets/digimon/greymon/4.png'),
    require('@/assets/digimon/greymon/5.png'),
    require('@/assets/digimon/greymon/6.png'),
    require('@/assets/digimon/greymon/7.png'),
    require('@/assets/digimon/greymon/8.png'),
    require('@/assets/digimon/greymon/9.png'),
    require('@/assets/digimon/greymon/10.png'),
    require('@/assets/digimon/greymon/11.png'),
    require('@/assets/digimon/greymon/12.png'),
    require('@/assets/digimon/greymon/13.png'),
    require('@/assets/digimon/greymon/14.png'),
  ],
  metalgreymon: [
    require('@/assets/digimon/metalgreymon/0.png'),
    require('@/assets/digimon/metalgreymon/1.png'),
    require('@/assets/digimon/metalgreymon/2.png'),
    require('@/assets/digimon/metalgreymon/3.png'),
    require('@/assets/digimon/metalgreymon/4.png'),
    require('@/assets/digimon/metalgreymon/5.png'),
    require('@/assets/digimon/metalgreymon/6.png'),
    require('@/assets/digimon/metalgreymon/7.png'),
    require('@/assets/digimon/metalgreymon/8.png'),
    require('@/assets/digimon/metalgreymon/9.png'),
    require('@/assets/digimon/metalgreymon/10.png'),
    require('@/assets/digimon/metalgreymon/11.png'),
    require('@/assets/digimon/metalgreymon/12.png'),
    require('@/assets/digimon/metalgreymon/13.png'),
    require('@/assets/digimon/metalgreymon/14.png'),
  ],
  wargreymon: [
    require('@/assets/digimon/wargreymon/0.png'),
    require('@/assets/digimon/wargreymon/1.png'),
    require('@/assets/digimon/wargreymon/2.png'),
    require('@/assets/digimon/wargreymon/3.png'),
    require('@/assets/digimon/wargreymon/4.png'),
    require('@/assets/digimon/wargreymon/5.png'),
    require('@/assets/digimon/wargreymon/6.png'),
    require('@/assets/digimon/wargreymon/7.png'),
    require('@/assets/digimon/wargreymon/8.png'),
    require('@/assets/digimon/wargreymon/9.png'),
    require('@/assets/digimon/wargreymon/10.png'),
    require('@/assets/digimon/wargreymon/11.png'),
    require('@/assets/digimon/wargreymon/12.png'),
    require('@/assets/digimon/wargreymon/13.png'),
    require('@/assets/digimon/wargreymon/14.png'),
  ],
}

// Overlays de estado (modelo Digital Monster: estados mostrados por símbolos sobre o sprite)
export const OVERLAYS = {
  skull: require('@/assets/ui/skull.png'),
  zzz: require('@/assets/ui/zzz.png'),
  grave: require('@/assets/ui/grave.png'),
} as const
